// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huwjvdqdnktddnmfmflw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1d2p2ZHFkbmt0ZGRubWZtZmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjUyNTYsImV4cCI6MjA3MzU0MTI1Nn0.cvKXfuu31RddKHfNfXm2TzVY5NJD6Cx-RnDsBFBKMJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});